### ISSUE TITLE
Destruct.jl is version capped

### ISSUE THREAD

**Issue by galenlynch** [spalato/Destruct.jl#3]
[discourse announcement](https://discourse.julialang.org/t/package-compatibility-caps/15301)

**Comment by spalato** [comment]
Thanks. Fixes should be in using Compat. Can you check the cap has been removed?

**Comment by galenlynch** [comment]
Hmm, it looks like it's still capped:
```
$ less Compat.toml                                                                                                                                                                    master
["1.0"]
julia = "0.6-0.7"
```
My impression is that you need to make a pull request to the Registry to fix the cap, now that it has been capped.

**Comment by spalato** [comment]
The updated version got picked up by attobot and the pull request is now merged.

https://github.com/JuliaLang/METADATA.jl/pull/18334

I think this should fix the cap. Can you confirm?

**Comment by galenlynch** [comment]
```
~/.j/r/G/D/Destruct$ less Compat.toml 
["1.0"]
julia = "0.6-0.7"

["1.1"]
julia = "0.6-1.1"
Compat = "0.0-1.2"
```
Looks good! Thank you!
